CREATE TABLE PATIENT_PROCEDURES
(ID				INT				IDENTITY(1,1)  PRIMARY KEY,
 NAME			NVARCHAR(40)	NOT NULL,
 DEPARTMENT		TINYINT			NOT NULL  REFERENCES DEPARTMENT_TYPE(ID), 
 PRACTITIONER	SMALLINT		NOT NULL  REFERENCES PRACTITIONERS(ID),
 PROCEDURE_DATE	DATE			NOT NULL)