CREATE TABLE PATIENT_APPOINTMENTS
(PATIENT_ID			INT			NOT NULL  REFERENCES PATIENTS(ID),
 APPOINTMENT_DATE	DATE		NOT NULL,
 PRACTITIONER_ID	SMALLINT	NOT NULL  REFERENCES PRACTITIONERS(ID),
 BLOOD_WORK			BIT			NOT NULL,
 PRIMARY KEY (PATIENT_ID, APPOINTMENT_DATE, PRACTITIONER_ID) );