create proc SUBMIT_DATE_SEARCH
	@StartDate date,
    @EndDate date
as

select PATIENT_RECORDS.SUBMISSION_DATE, PATIENTS.FIRST_NAME, PATIENTS.LAST_NAME
from PATIENT_RECORDS join PATIENTS on PATIENT_RECORDS.PATIENT_ID = PATIENTS.ID
where SUBMISSION_DATE >= @StartDate and SUBMISSION_DATE <= @EndDate;