create proc BILLABLE_ITEMS_SEARCH
	@PatientID int
as

select PATIENT_RECORDS.PATIENT_ID, PATIENTS_BILLABLE_ITEMS.ITEM_DESCRIPTION,
	PRACTITIONERS.FIRST_NAME as PRACTITIONER_FIRST_NAME,
	PRACTITIONERS.LAST_NAME as PRACTITIONER_LAST_NAME

from PATIENTS_BILLABLE_ITEMS
join PRACTITIONERS on PATIENTS_BILLABLE_ITEMS.ASSIGNED_BY_PRACTITIONER_ID = PRACTITIONERS.ID
join PATIENT_RECORDS on PATIENTS_BILLABLE_ITEMS.PATIENT_RECORDS_ID = PATIENT_RECORDS.RECORDS_ID

where PATIENT_RECORDS.PATIENT_ID = @PatientID;