SELECT PATIENTS.FIRST_NAME, PATIENTS.LAST_NAME,
	CASE
		WHEN DATEDIFF(YEAR,PATIENTS.DATE_OF_BIRTH,GETDATE()) < 1 THEN 'INFANT'
		WHEN DATEDIFF(YEAR,PATIENTS.DATE_OF_BIRTH,GETDATE()) < 3 THEN 'TODDLER'
		WHEN DATEDIFF(YEAR,PATIENTS.DATE_OF_BIRTH,GETDATE()) < 11 THEN 'CHILD'
		WHEN DATEDIFF(YEAR,PATIENTS.DATE_OF_BIRTH,GETDATE()) < 17 THEN 'TEENAGER'
		WHEN DATEDIFF(YEAR,PATIENTS.DATE_OF_BIRTH,GETDATE()) < 62 THEN 'ADULT'
		ELSE 'SENIOR'
	END AS AGE_GROUP
FROM PATIENTS ORDER BY AGE_GROUP;