SELECT PATIENTS.FIRST_NAME, PATIENTS.LAST_NAME, PATIENT_RECORDS.ROOM_NUMBER,
	PATIENTS_BILLABLE_ITEMS.ITEM_DESCRIPTION, PRACTITIONERS.FIRST_NAME,
	PRACTITIONERS.LAST_NAME, DEPARTMENT_TYPE.DEPARTMENT_TYPE
FROM

PATIENTS JOIN PATIENT_RECORDS
ON PATIENTS.ID = PATIENT_RECORDS.PATIENT_ID

JOIN PATIENTS_BILLABLE_ITEMS
ON PATIENT_RECORDS.RECORDS_ID = PATIENTS_BILLABLE_ITEMS.PATIENT_RECORDS_ID

JOIN PRACTITIONERS
ON PATIENTS_BILLABLE_ITEMS.ASSIGNED_BY_PRACTITIONER_ID = PRACTITIONERS.ID

JOIN DEPARTMENT_TYPE
ON PRACTITIONERS.STAFF_TYPE = DEPARTMENT_TYPE.ID;