create view DISCHARGED_PATIENTS as
select PATIENTS.FIRST_NAME, PATIENTS.LAST_NAME, PATIENTS.DATE_OF_BIRTH from
PATIENTS where PATIENTS.ID not in
(select PATIENT_ID from PATIENT_RECORDS where IS_DISCHARGED = 0)
order by LAST_NAME offset 0 rows;