create view BILLABLE_TOTALS_PER_VISIT as
select PATIENTS.FIRST_NAME, PATIENTS.LAST_NAME, PATIENT_RECORDS.SUBMISSION_DATE, 
case
	when PATIENT_RECORDS.IS_DISCHARGED = 1 then PATIENT_RECORDS.DISCHARGE_DATE
	else 'not discharged'
end as DISCHARGE_STATUS, TOTAL_BILLABLE from

PATIENT_RECORDS join PATIENTS on PATIENT_RECORDS.PATIENT_ID = PATIENTS.ID

join
(select PATIENT_RECORDS_ID, sum(PRICE * QUANTITY) as TOTAL_BILLABLE from PATIENTS_BILLABLE_ITEMS group by PATIENT_RECORDS_ID) as TOTAL_TABLE
on TOTAL_TABLE.PATIENT_RECORDS_ID = PATIENT_RECORDS.RECORDS_ID;