CREATE TABLE PATIENT_RECORDS
(RECORDS_ID					INT				NOT NULL  IDENTITY(1,1)  PRIMARY KEY,
 PATIENT_ID					INT				NOT NULL  REFERENCES PATIENTS(ID),
 SUBMISSION_DATE			DATE			NOT NULL,
 ROOM_NUMBER				CHAR(4)			NOT NULL,
 INSURANCE_POLICY_NUMBER	NVARCHAR(20)	NOT NULL,
 DISCHARGE_DATE				DATE			NOT NULL);