CREATE TABLE PATIENTS
(ID					INT				NOT NULL  IDENTITY(1000000,1)  PRIMARY KEY,
 FIRST_NAME			NVARCHAR(20)	NOT NULL,
 LAST_NAME			NVARCHAR(20)	NOT NULL,
 DATE_OF_BIRTH		DATE			NOT NULL,
 SSN				INT				NOT NULL,
 MAIL_STREET		NVARCHAR(50)	NOT NULL,
 MAIL_CITY			NVARCHAR(30)	NOT NULL,
 MAIL_STATE			CHAR(2)			NOT NULL,
 MAIL_ZIP			INT				NOT NULL,
 MAIL_COUNTRY		CHAR(2)			NOT NULL);

CREATE TABLE STAFF_TYPE
(ID					TINYINT			NOT NULL  PRIMARY KEY,
 STAFF_TYPE			NVARCHAR(20)	NOT NULL);

INSERT INTO STAFF_TYPE VALUES
(1, 'Physician'),
(2, 'Surgeon'),
(3, 'Nurse'),
(4, 'Lab'),
(5, 'Administrative');

SELECT * INTO PRACTITIONERS FROM PATIENTS WHERE 1 = 2;

ALTER TABLE PRACTITIONERS
 DROP COLUMN ID, MAIL_COUNTRY;

ALTER TABLE PRACTITIONERS
 ADD	ID				SMALLINT	NOT NULL  IDENTITY(1000,1)  PRIMARY KEY,
		STAFF_TYPE		TINYINT		NOT NULL  REFERENCES STAFF_TYPE(ID),
		YEARLY_SALARY	MONEY		NOT NULL,
		YEARLY_BONUS	MONEY		NOT NULL;

CREATE TABLE DEPARTMENT_TYPE
(ID					TINYINT			NOT NULL  PRIMARY KEY,
 DEPARTMENT_TYPE	NVARCHAR(30)	NOT NULL);

INSERT INTO DEPARTMENT_TYPE VALUES
(1, 'Emergency'),
(2, 'Cardiology'),
(3, 'Neurology'),
(4, 'Intensive Care Unit'),
(5, 'Labor & Delivery'),
(6, 'Administration'),
(7, 'Pediatric');